const {test}=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const fs=require('fs');
function app(t){const d=new JSDOM(require("../app_sources").readApp('_assets/list.html').replace('<script src="data.js"></script>','<script>let DATA=[];let DAILY_TASKS=[];</script>'),{runScripts:'dangerously',url:'http://localhost'});t.after(()=>d.window.close());return d.window;}
test('分析は未設定と期限超過を区別し、カードへ移動できる',t=>{const w=app(t);w.eval('DATA='+JSON.stringify([{'カテゴリー':'A','名前(あだ名)':'予定なし','アクション日':'2026/09/20'},{'カテゴリー':'B','名前(あだ名)':'予定あり','次会う日':'2026/09/29'},{'カテゴリー':'D','名前(あだ名)':'対象外'}]));w.DAILY_TASKS={date:'2026-09-27',tasks:[]};w.setView('analytics');assert.equal(w.document.querySelector('[data-metric="lateContacts"]').textContent,'1');assert.equal(w.document.querySelector('[data-metric="unplanned"]').textContent,'1');w.document.querySelector('[data-analysis-person]').click();assert.equal(w.document.body.className,'view-garden');});
test('日別集計は同日上書きで56日保存し、個人情報を残さない',()=>{const {appendAnalysisLog}=require('../analysis_history');const log=appendAnalysisLog([{date:'2026-01-01',overdue:2},{date:'2026-09-27',overdue:9}],{date:'2026-09-27',tasks:[{section:'selfOverdue',title:'secret'}]},[{'カテゴリー':'A','名前(あだ名)':'secret'}]);assert.equal(log.length,1);assert.equal(log[0].overdue,1);assert.ok(!JSON.stringify(log).includes('secret'));});


test('滞留カードを削除し、人脈の分析と期限切れ件数は表示する',t=>{const w=app(t);w.DAILY_TASKS={date:'2026-09-27',tasks:[{id:'x',section:'selfOverdue',title:'作業',owner:'自分',overdueDays:2}],analysisLog:[{date:'2026-09-26',overdue:2}]};w.setView('analytics');const wrap=w.document.getElementById('analyticswrap');assert.doesNotMatch(wrap.textContent,/タスクの滞留状況|長く残っているタスク|日別の期限切れ件数|7日前から/);assert.equal(wrap.querySelector('[data-chart="trend"]'),null);assert.equal(wrap.querySelector('[data-chart="owners"]'),null);assert.equal(wrap.querySelector('[data-metric="overdue"]').textContent,'1');assert.match(wrap.textContent,/人脈のフォロー状況|今週の行動候補/);});
