'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),target=path.join(root,'_preview/field-quest-e2e');
const {readApp}=require('../app_sources'),{writeBundle}=require('../artifact_bundle'),{gateHtmlForTest,encryptForTest}=require('../build'),M=require('../_assets/js/field-model');
async function run(before=false){
 fs.mkdirSync(target,{recursive:true});const today='2026-10-05',month='2026-10',now=new Date(today+'T12:00:00+09:00');
 const contacts=[1,2,3].map(n=>({_row:n+1,_version:'fixture-v1','\u540d\u524d(\u30cb\u30c3\u30af\u30cd\u30fc\u30e0)':'Fixture '+n,'\u30ab\u30c6\u30b4\u30ea\u30fc':'A'}));
 const report={month,activityDate:'2026-10-04',reportDate:today,values:{orientation:2,introductions:3,individual:4,first_individual:1,new_friends:2},goals:Object.fromEntries(M.keys.map(k=>[k,10])),partial:true};
 const persons=contacts.map(p=>({id:'quest-person-fixture-'+p._row,name:p['\u540d\u524d(\u30cb\u30c3\u30af\u30cd\u30fc\u30e0)'],row:p._row}));
 let state={goals:{[month]:{prospects:3,metrics:report.goals}},persons,records:[{id:'quest-record-fixture-001',personId:persons[0].id,kind:'orientation',status:'proposed',date:'2026-10-06',dueDate:today,purpose:'\u30aa\u30ea\u30a8\u30f3\u306e\u65e5\u7a0b\u3092\u6c7a\u3081\u308b',outcomeConfirmed:false,newPersonForMonth:true},{id:'quest-record-fixture-002',personId:persons[1].id,kind:'individual',status:'confirmed',date:'2026-10-06',dueDate:'2026-10-06',purpose:'\u500b\u5225\u306e\u76f8\u8ac7\u4e88\u5b9a',outcomeConfirmed:false,newPersonForMonth:true}]};state=M.createMission(state,report,month,today);
 const enc=await encryptForTest({contacts,dailyTasks:{date:today,tasks:[],sources:{}},fieldProgress:{months:[report]}},'quest-fixture');
 const html=readApp(path.join(root,'_assets/list.html')).replace(/const EVENTS = \[[\s\S]*?\];/,'const EVENTS = [];').replace(/const FREE_SLOTS = \[[\s\S]*?\];/,'const FREE_SLOTS = [];').replace(/const API_URL = "[^"]+"/,'const API_URL = "/api"').replace('<script src="data.js"></script>',gateHtmlForTest(enc,today));writeBundle(path.join(target,'comlist.html'),html,path.join(root,'_assets'));
 let writes=0;const server=http.createServer(async(req,res)=>{if(req.url==='/api'){let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);if(!['read','taskState','fieldGoalsRead'].includes(body.action))writes++;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body.action==='fieldGoalsRead'?{ok:true,state,version:'quest-fixture-version'}:body.action==='taskState'?{ok:true,done:{},date:today}:{ok:true,records:contacts,events:[]}));return;}try{const file=path.resolve(target,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(target+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const {chromium}=require('C:/Users/ryupr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),results=[];
 try{for(const width of [1280,390]){const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage();await page.clock.install({time:now});await page.clock.pauseAt(now);await page.goto('http://127.0.0.1:'+server.address().port+'/comlist.html');await page.locator('#lockpass').fill('quest-fixture');await page.locator('#lockbtn').click();await page.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');await page.evaluate(s=>{FIELD_GOALS_STATE=FieldGoalsModel.validate(s);FIELD_GOALS_VERSION='fixture-v1';FIELD_GOALS_PHASE='\u540c\u671f\u6e08\u307f';},state);await page.locator('[data-view=field]').click();await page.locator('#fieldwrap').screenshot({path:path.join(target,(before?'before-':'after-')+width+'.png')});
 if(!before){assert.equal(await page.locator('[data-field-record-today]').count(),5);assert.equal(await page.locator('.field-quest-next').count(),1);assert.equal(await page.locator('.field-mission-gauge').count(),5);assert.equal(await page.locator('.field-week-quest').count(),1);assert.equal(await page.evaluate(()=>document.getElementById('field-mission-board').compareDocumentPosition(document.querySelector('.field-calendar'))&Node.DOCUMENT_POSITION_FOLLOWING),4);await page.locator('[data-field-record-today=individual]').click();assert.equal(await page.locator('#field-goal-dialog [name=status]').inputValue(),'completed');assert.equal(await page.locator('#field-goal-dialog [name=date]').inputValue(),today);assert.equal(await page.locator('#field-goal-dialog [name=outcome]').isChecked(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('#field-goal-dialog').count(),0);await page.locator('.field-quest-next [data-field-edit]').click();assert.equal(await page.locator('#field-goal-dialog [name=purpose]').inputValue(),'\u30aa\u30ea\u30a8\u30f3\u306e\u65e5\u7a0b\u3092\u6c7a\u3081\u308b');await page.locator('#field-goal-dialog [data-cancel]').click();await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>renderFieldProgress());assert.equal(await page.locator('.field-mission-board').evaluate(e=>e.classList.contains('reduced-motion')),true);}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);results.push({width,before,noOverflow:true,writes:0});await context.close();}assert.equal(writes,0);fs.writeFileSync(path.join(target,before?'before-result.json':'result.json'),JSON.stringify({results,writes,productionRequests:0},null,2));console.log('FIELD_QUEST_BROWSER: '+JSON.stringify({results,writes,productionRequests:0}));}finally{await browser.close();await new Promise(r=>server.close(r));}
}
if(require.main===module)run(process.argv.includes('--capture-before')).catch(e=>{console.error(e);process.exitCode=1});module.exports={run};
