'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),{readApp}=require('../app_sources'),{writeBundle}=require('../artifact_bundle'),{gateHtmlForTest,encryptForTest}=require('../build'),M=require('../_assets/js/field-model');
async function run(){
 const date=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),month=date.slice(0,7),tomorrow=new Date(date+'T00:00:00Z');tomorrow.setUTCDate(tomorrow.getUTCDate()+1);
 const contacts=[{_row:2,_version:'fixture-contact-v1','カテゴリー':'A','名前(あだ名)':'目標テストの相手','アクション日':date,_contactState:{status:'waiting',date:date.slice(0,8)+'01'}},{_row:3,_version:'fixture-contact-v2','カテゴリー':'B','名前(あだ名)':'約束は明日の相手','アクション日':tomorrow.toISOString().slice(0,10)},{_row:4,_version:'fixture-contact-v3','カテゴリー':'C','名前(あだ名)':'月目標テスト3人目','アクション日':tomorrow.toISOString().slice(0,10)}];
 const report={month,activityDate:date,reportDate:date,partial:true,url:'https://app.notion.com/fixture',values:{orientation:0,introductions:0,individual:1,first_individual:0,new_friends:0},goals:{orientation:2,introductions:10,individual:30,first_individual:15,new_friends:40}};
 const enc=await encryptForTest({contacts,dailyTasks:{date,tasks:[],sources:{}},fieldProgress:{months:[report]}},'fixture-pass');
 const target=path.join(root,'_preview','field-goals-e2e');fs.mkdirSync(target,{recursive:true});
 const html=readApp(path.join(root,'_assets/list.html')).replace(/const EVENTS = \[[\s\S]*?\];/,'const EVENTS = [];').replace(/const FREE_SLOTS = \[[\s\S]*?\];/,'const FREE_SLOTS = [];').replace(/const API_URL = "[^"]+"/,'const API_URL = "/api"').replace('<script src="data.js"></script>',gateHtmlForTest(enc,date)).replace(/renderEvents\(\);\s*\nsetView\("today"\);/,'/* unlock renders */');writeBundle(path.join(target,'comlist.html'),html,path.join(root,'_assets'));
 let state=M.empty(),version='v1',receipt='',writes=0,offline=false,lose=false;const requests=[];
 const server=http.createServer(async(req,res)=>{
  if(req.url==='/api'){let raw='';for await(const c of req)raw+=c;const b=JSON.parse(raw);let j;
   if(b.action==='fieldGoalsRead')j=offline?{ok:false,error:'offline'}:{ok:true,state,version,requestId:receipt};
   else if(b.action==='fieldGoalsWrite'){requests.push(b);if(offline)j={ok:false,error:'offline'};else if(b.requestId===receipt)j={ok:true,state,version,requestId:receipt};else if(b.version!==version)j={ok:false,error:'conflict'};else{state=M.validate(b.state);version='v'+(Number(version.slice(1))+1);receipt=b.requestId;writes++;j={ok:true,state,version,requestId:receipt};if(lose){lose=false;j={ok:false,error:'response lost'};}}}
   else if(b.action==='taskState')j={ok:true,date:b.date,done:{}};else if(b.action==='read')j=b.what==='contacts'?{ok:true,records:contacts}:{ok:true,events:[]};else j={ok:false,error:'unexpected action'};
   res.setHeader('Content-Type','application/json');res.end(JSON.stringify(j));return;
  }
  try{const rel=new URL(req.url,'http://local').pathname.slice(1)||'comlist.html',file=path.resolve(target,rel);if(!file.startsWith(target+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('not found');}
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const runtime=process.env.CODEX_NODE_MODULES||'C:/Users/ryupr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules', {chromium}=require(path.join(runtime,'playwright'));
 const exe=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',chromium.executablePath()].find(f=>fs.existsSync(f));const browser=await chromium.launch({headless:true,executablePath:exe});const tests=[];
 try{
  const contexts=[];async function fresh(width){const c=await browser.newContext({viewport:{width,height:900}});contexts.push(c);await c.route('https://**/*',r=>r.abort());await c.addInitScript(()=>localStorage.setItem('comunitylisttolevel9','fixture-token'));const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.fixtureErrors=errors;await p.goto(base+'/comlist.html');await unlock(p);await p.locator('[data-view="field"]').click();await p.waitForFunction(()=>!FIELD_GOALS_READ_BUSY);return p;}
  async function unlock(p){await p.locator('#lockpass').fill('fixture-pass');await p.locator('#lockbtn').click();await p.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');}
  const pc=await fresh(1280),mobile=await fresh(390);assert.match(await pc.locator('#fieldwrap').textContent(),/0人確認済み.*目標 3人/s);assert.match(await pc.locator('#fieldwrap').textContent(),/個別.*実績 1.*目標 30件/s);assert.equal(await mobile.locator('[data-field-candidate="3"]').count(),0);assert.doesNotMatch(await pc.locator('#fieldwrap').textContent(),/確定予定と未確保|今日誰に何をするか/);assert.equal(await pc.locator('#field-record-add').count(),0);tests.push('成果・単位・活動日・削除した2項目の非表示');
  await pc.locator('[data-field-plan-kind="introductions"]').first().click();await pc.locator('#field-goal-dialog [data-cancel]').click();assert.equal(writes,0);tests.push('入力キャンセル');
  await pc.locator('[data-field-plan-kind="introductions"]').first().click();await pc.locator('#field-goal-dialog [name=person]').selectOption('row:2');await pc.locator('#field-goal-dialog [name=purpose]').fill('本人の判断で紹介の機会を相談');await pc.locator('#field-goal-dialog [name=status]').selectOption('confirmed');await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);assert.equal(state.records.length,1);assert.match(await pc.locator('#fieldwrap').textContent(),/0人確認済み/);assert.equal(await pc.locator('.field-outcome-cells .is-planned').count(),1);tests.push('確定予定だけでは達成しない');
  await pc.evaluate(()=>openFieldRecordEditor(fieldGoalsToday().slice(0,7),fieldGoalsData().records[0].id));await pc.locator('#field-goal-dialog [name=status]').selectOption('completed');await pc.locator('#field-goal-dialog [name=outcome]').check();await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);assert.match(await pc.locator('#fieldwrap').textContent(),/1人確認済み/);
  await pc.evaluate(()=>{window.FIELD_PROGRESS.months[0].values.introductions=1;renderFieldProgress();});const metrics=await pc.locator('.field-goal-metrics').textContent();assert.match(metrics,/紹介実績 1/);assert.doesNotMatch(metrics,/紹介実績 2/);tests.push('予定から実施・日報更新の二重加算防止');
  await mobile.evaluate(()=>refreshFieldGoals());await mobile.locator('#field-goal-edit').click();await mobile.locator('#field-goal-dialog [name=prospects]').fill('5');await pc.locator('#field-goal-edit').click();await pc.locator('#field-goal-dialog [name=prospects]').fill('4');await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);await mobile.locator('#field-goal-dialog button[type=submit]').click();await mobile.waitForFunction(()=>!FIELD_GOALS_BUSY);assert.equal(state.goals[month].prospects,4);assert.equal(await mobile.evaluate(m=>FIELD_GOALS_PENDING.state.goals[m].prospects,month),5);assert.match(await mobile.locator('#field-goals-status').textContent(),/競合/);tests.push('PC・スマホの同時編集と入力保持');
  mobile.once('dialog',d=>d.accept());await mobile.locator('#field-goals-discard').click();await mobile.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_READ_BUSY);
  offline=true;await pc.locator('#field-goal-edit').click();await pc.locator('#field-goal-dialog [name=prospects]').fill('6');await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_BUSY);const id=await pc.evaluate(()=>FIELD_GOALS_PENDING.requestId);await pc.reload();await unlock(pc);await pc.locator('[data-view="field"]').click();await pc.waitForFunction(()=>!FIELD_GOALS_READ_BUSY);assert.equal(await pc.evaluate(()=>FIELD_GOALS_PENDING.requestId),id);offline=false;lose=true;await pc.locator('#field-goals-retry').click();await pc.waitForFunction(()=>!FIELD_GOALS_BUSY);const count=writes;await pc.locator('#field-goals-retry').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);assert.equal(writes,count);assert.equal(requests.at(-1).requestId,id);tests.push('通信失敗・再読込・同一ID再試行・応答消失');
  await pc.evaluate(()=>openFieldRecordEditor(fieldGoalsToday().slice(0,7),fieldGoalsData().records[0].id));await pc.locator('#field-goal-dialog [name=status]').selectOption('cancelled');await pc.locator('#field-goal-dialog [name=outcome]').uncheck();await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);assert.match(await pc.locator('#fieldwrap').textContent(),/0人確認済み/);assert.equal(state.records.length,1);tests.push('取消は履歴を保持し成果から除外');
  await pc.locator('#field-goal-edit').click();await pc.locator('#field-goal-dialog [name=prospects]').fill('3');for(const k of M.keys)await pc.locator('#field-goal-dialog [name='+k+']').fill('');await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);
  pc.once('dialog',d=>d.accept());await pc.locator('#field-mission-start').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);assert.equal(state.missions.length,1);assert.equal(await pc.locator('.field-week-stamp').count(),0);
  for(const person of contacts){await pc.locator('[data-field-plan-kind="introductions"]').first().click();await pc.locator('#field-goal-dialog [name=person]').selectOption({label:person['名前(あだ名)']});await pc.locator('#field-goal-dialog [name=purpose]').fill('架空データで紹介につながった確認');await pc.locator('#field-goal-dialog [name=status]').selectOption('completed');await pc.locator('#field-goal-dialog [name=outcome]').check();await pc.locator('#field-goal-dialog button[type=submit]').click();await pc.waitForFunction(()=>!FIELD_GOALS_PENDING&&!FIELD_GOALS_BUSY);}
  await pc.waitForFunction(()=>!FIELD_MISSION_EFFECT_PENDING&&FIELD_MISSION_CELEBRATED['month:'+fieldGoalsToday().slice(0,7)]===true);assert.equal(await pc.locator('.field-outcome-cells .is-done').count(),3);assert.equal(await pc.locator('.field-week-stamp').count(),1);assert.equal(await pc.locator('#field-month-celebration').count(),1);tests.push('週スタンプ・月3人の達成マス・お祝い');
  await pc.reload();await unlock(pc);await pc.locator('[data-view="field"]').click();await pc.waitForFunction(()=>!FIELD_GOALS_READ_BUSY);assert.equal(await pc.locator('.field-celebrate-once').count(),0);assert.equal(await pc.locator('#field-mission-announcement').textContent(),'');tests.push('再読込・同期で達成演出を再発火しない');
  await pc.locator('#field-goal-edit').focus();const beforeKeyboard=writes;await pc.keyboard.press('Enter');assert.equal(await pc.locator('#field-goal-dialog').isVisible(),true);await pc.keyboard.press('Escape');assert.equal(await pc.locator('#field-goal-dialog').count(),0);assert.equal(writes,beforeKeyboard);tests.push('キーボード入力・Escape取消');
  await mobile.emulateMedia({reducedMotion:'reduce'});await mobile.evaluate(()=>refreshFieldGoals());await mobile.waitForFunction(()=>!FIELD_MISSION_EFFECT_PENDING);assert.equal(await mobile.locator('#field-reduce-motion').isChecked(),true);assert.equal(await mobile.locator('#field-mission-board').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await mobile.locator('[role=progressbar]').count(),5);tests.push('動きを減らす設定・アクセシブルな5ゲージ');
  assert.ok(await mobile.locator('body').evaluate(e=>e.scrollWidth<=innerWidth));await pc.screenshot({path:path.join(target,'pc.png'),fullPage:true});await mobile.screenshot({path:path.join(target,'mobile.png'),fullPage:true});assert.deepEqual(pc.fixtureErrors,[]);assert.deepEqual(mobile.fixtureErrors,[]);tests.push('PC・スマホ表示と横幅');
  const result={tests,writes,productionRequests:0};fs.writeFileSync(path.join(target,'result.json'),JSON.stringify(result,null,2)+'\n');return result;
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
module.exports={run};
if(require.main===module)run().then(r=>console.log('FIELD_GOALS_BROWSER: OK '+JSON.stringify(r))).catch(e=>{console.error(e);process.exitCode=1;});
