'use strict';
// All data and API responses are synthetic. HTTPS requests are blocked.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
async function run(){
 const root=path.resolve(__dirname,'..'),target=path.join(root,'_preview/action-calendar-e2e');fs.mkdirSync(target,{recursive:true});
 const now=new Date('2026-10-04T10:00:00+09:00'),today='2026-10-04',month='2026-10',M=require('../_assets/js/field-model');
 const person={id:'person-browser-calendar001',name:'検証用の相手',row:2},state={goals:{[month]:{prospects:3,metrics:{orientation:10,introductions:10,individual:10,first_individual:10,new_friends:10}}},persons:[person],records:M.keys.map((kind,i)=>({id:'record-browser-calendar00'+i,personId:person.id,kind,status:'confirmed',date:'2026-10-05',dueDate:'2026-10-05',purpose:'検証用の確定予定',outcomeConfirmed:false,newPersonForMonth:true})),missions:[]};
 const report={month,activityDate:'2026-10-03',reportDate:'2026-10-04',values:Object.fromEntries(M.keys.map(k=>[k,4])),goals:Object.fromEntries(M.keys.map(k=>[k,10])),partial:true};
 const daily={date:today,tasks:[],calendar:[],sources:{}},availability={events:[],info:{source:'primary',fetchedAt:now.toISOString(),rangeStart:today+'T00:00:00+09:00',rangeEnd:'2026-11-05T00:00:00+09:00',complete:true}};
 const {gateHtmlForTest,encryptForTest}=require('../build'),{readApp}=require('../app_sources'),{writeBundle}=require('../artifact_bundle');
 const enc=await encryptForTest({contacts:[{_row:2,'名前(あだ名)':person.name,'カテゴリー':'A'}],dailyTasks:daily,fieldProgress:{months:[report]},calendarAvailability:availability},'action-calendar-fixture');
 const html=readApp(path.join(root,'_assets/list.html')).replace(/const EVENTS = \[[\s\S]*?\];/,'const EVENTS = [];').replace(/const FREE_SLOTS = \[[\s\S]*?\];/,'const FREE_SLOTS = [];').replace(/const API_URL = "[^"]+"/,'const API_URL = "/api"').replace('<script src="data.js"></script>',gateHtmlForTest(enc,today)).replace(/renderEvents\(\);\s*\nsetView\("today"\);/,'/* unlock renders */');writeBundle(path.join(target,'comlist.html'),html,path.join(root,'_assets'));
 let mode='ok',writes=0,reads=0;
 const server=http.createServer(async(req,res)=>{if(req.url==='/api'){let raw='';for await(const part of req)raw+=part;const b=JSON.parse(raw);let j={ok:true};if(b.action==='read'&&b.what==='calendarAvailability'){reads++;if(mode==='fail'){res.statusCode=503;res.end('{}');return;}j={ok:true,calendarAvailability:JSON.parse(JSON.stringify(availability))};if(mode==='stale')j.calendarAvailability.info.fetchedAt=new Date(now.getTime()-4*3600000).toISOString();if(mode==='partial')j.calendarAvailability.info.complete=false;}else if(b.action==='fieldGoalsRead')j={ok:true,state,version:'fixture-version'};else if(b.action==='taskState')j={ok:true,done:{},date:b.date};else if(b.action==='read')j={ok:true,records:[],events:[]};else{writes++;j={ok:false,error:'writes forbidden in this test'};}res.setHeader('Content-Type','application/json');res.end(JSON.stringify(j));return;}try{const rel=new URL(req.url,'http://local').pathname.slice(1)||'comlist.html',file=path.resolve(target,rel);if(!file.startsWith(target+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('not found');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const runtime=process.env.CODEX_NODE_MODULES||'C:/Users/ryupr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules',{chromium}=require(path.join(runtime,'playwright'));const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe',chromium.executablePath()].find(f=>fs.existsSync(f)),browser=await chromium.launch({headless:true,executablePath}),results=[];
 try{for(const width of [1280,390]){mode='ok';const context=await browser.newContext({viewport:{width,height:900}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:now});await page.clock.pauseAt(now);await page.goto('http://127.0.0.1:'+server.address().port+'/comlist.html');await page.evaluate(()=>localStorage.setItem('comunitylisttolevel9','fixture-token'));await page.locator('#lockpass').fill('action-calendar-fixture');await page.locator('#lockbtn').click();await page.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');await page.evaluate(()=>setWriteToken('fixture-token'));
await page.evaluate(s=>{FIELD_GOALS_STATE=FieldGoalsModel.validate(s);FIELD_GOALS_VERSION='fixture-version';},state);
 await page.locator('[data-view=field]').click();await page.waitForFunction(()=>document.querySelectorAll('.field-calendar-day').length===42);assert.equal(await page.locator('.field-calendar-day').first().locator('div').count(),5);assert.match(await page.locator('.field-calendar').textContent(),/残り 28 日/);assert.match(await page.locator('.field-calendar-summary-grid').textContent(),/目標 10件 ／ 実績 4件/);await page.locator('[data-fc-mode=week]').click();assert.equal(await page.locator('.field-calendar-day').count(),7);await page.locator('[data-fc-nav="-1"]').click();assert.match(await page.locator('.field-calendar-controls').textContent(),/2026-09-21〜2026-09-27/);if(width===390)assert.equal(await page.locator('.field-calendar-day:visible').count(),7);await page.locator('[data-fc-nav="0"]').click();await page.locator('[data-fc-mode=month]').click();await page.screenshot({path:path.join(target,'field-'+width+'.png')});await page.locator('.field-calendar-day:not(.outside)').first().screenshot({path:path.join(target,'day-'+width+'.png')});
 await page.locator('[data-view=calendar]').click();assert.equal(await page.locator('.slot-candidate').count(),0);assert.equal(await page.evaluate(()=>document.getElementById('slots').compareDocumentPosition(document.getElementById('calframe'))&Node.DOCUMENT_POSITION_FOLLOWING),4);await page.locator('.slot-settings summary').click();await page.locator('[name=buffer]').fill('10');await page.locator('#slot-settings-form button').click();await page.waitForFunction(()=>document.querySelectorAll('.slot-week-day').length===7);assert.match(await page.locator('.slot-candidate').first().textContent(),/10:00〜11:30/);assert.match(await page.locator('.slot-candidate').first().getAttribute('aria-label'),/2026-10-04/);await page.locator('#slot-week-next').click();assert.equal(await page.locator('.slot-week-day').count(),7);assert.ok(await page.locator('.slot-candidate').count()>3);let weeks=1;while(!await page.locator('#slot-week-next').isDisabled()){await page.locator('#slot-week-next').click();weeks++;assert.ok(await page.locator('.slot-candidate').count()>0);}assert.ok(weeks>=4);assert.equal(await page.locator('.slot-week-day').first().getAttribute('data-slot-date'),'2026-11-02');while(!await page.locator('#slot-week-prev').isDisabled())await page.locator('#slot-week-prev').click();await page.locator('#slots').scrollIntoViewIfNeeded();await page.locator('#slots').screenshot({path:path.join(target,'slots-'+width+'.png')});
 await context.route('https://calendar.google.com/calendar/render?**',r=>r.fulfill({contentType:'text/html',body:'<p>Mock Google Calendar new event</p>'}));const link=await page.locator('[data-slot-index="0"]').getAttribute('href'),google=new URL(link);assert.equal(google.searchParams.get('dates'),'20261004T010000Z/20261004T023000Z');assert.equal(google.searchParams.get('ctz'),'Asia/Tokyo');assert.equal(google.searchParams.get('text'),'\u4e88\u5b9a');await page.evaluate(()=>{window.open=()=>{throw Error('popup blocked');};});await page.locator('[data-slot-index="0"]').click();await page.waitForURL('https://calendar.google.com/**');assert.equal(page.url(),link);await page.goBack();if(await page.locator('#lockpass').isVisible()){await page.locator('#lockpass').fill('action-calendar-fixture');await page.locator('#lockbtn').click();}await page.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');await page.locator('[data-view=calendar]').click();assert.ok(await page.locator('.slot-candidate').count()>0);assert.equal(await page.locator('#eventEditor').isHidden(),true);
 mode='fail';await page.locator('#slot-refresh').click();await page.waitForFunction(()=>!calendarSlotsBusy);assert.equal(await page.locator('.slot-candidate').count(),0);assert.match(await page.locator('#slots').textContent(),/取得に失敗/);await page.reload();await page.locator('#lockpass').fill('action-calendar-fixture');await page.locator('#lockbtn').click();await page.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');await page.locator('[data-view=calendar]').click();assert.equal(await page.locator('.slot-candidate').count(),0);assert.equal(await page.evaluate(()=>CALENDAR_SLOT_PREFS.buffer),10);
 for(const phase of ['stale','partial']){mode=phase;await page.locator('#slot-refresh').click();await page.waitForFunction(()=>!calendarSlotsBusy);assert.equal(await page.locator('.slot-candidate').count(),0);}mode='ok';await page.locator('#slot-refresh').click();await page.waitForFunction(()=>document.querySelectorAll('.slot-week-day').length===7);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);results.push({width,monthWeek:true,allFiveMetrics:true,weeklySlots:true,monthHorizon:true,googleTemplate:true,backPreserved:true,popupIndependent:true,failedReloadBlocked:true,staleAndPartialBlocked:true,settingsEncrypted:true,noOverflow:true});await context.close();}
 assert.equal(writes,0);fs.writeFileSync(path.join(target,'result.json'),JSON.stringify({results,reads,writes,productionRequests:0},null,2));console.log('ACTION_CALENDAR_BROWSER: '+JSON.stringify({results,reads,writes,productionRequests:0}));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
