'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
async function run(){
 const root=path.resolve(__dirname,'..'),target=path.join(root,'_preview/calendar-e2e');fs.mkdirSync(target,{recursive:true});
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),previous=new Date(today+'T00:00:00Z');previous.setUTCDate(previous.getUTCDate()-1);const yesterday=previous.toISOString().slice(0,10);
 const meta=(eventId,title,description,allDay=false)=>({source:'primary',eventId,title,location:'',description,allDay,detailsAvailable:true});
 const rows=[[yesterday+'T00:00',today+'T23:59',meta('fixture-long','検証用・日またぎイベント','検証用の会場情報')],[today+'T08:00',today+'T08:30',meta('fixture-short','検証用・朝の登録','   ')]];
 const daily=require('../calendar_schedule').applyCalendarSchedule({date:today,tasks:[],calendar:[{title:'予定'}],sources:{calendar:{ok:true},notion:{ok:true},gmail:{ok:true,checkedThreads:0,uniqueThreads:0}}},rows,today);
 const {gateHtmlForTest,encryptForTest}=require('../build'),{readApp}=require('../app_sources'),{writeBundle}=require('../artifact_bundle');
 const enc=await encryptForTest({contacts:[{_row:2,'仲間づくりアドバイス':'本人の希望：検証用の旅行\n未確認点：本人のペース\n次に聞く質問：どんな働き方を望みますか\n次の一歩：話せる時間を本人と相談','名前(あだ名)':'検証用人脈','カテゴリー':'A'}],dailyTasks:daily},'calendar-fixture-pass');
 const source=readApp(path.join(root,'_assets/list.html')).replace(/const EVENTS = \[[\s\S]*?\];/,'const EVENTS = [];').replace(/const FREE_SLOTS = \[[\s\S]*?\];/,'const FREE_SLOTS = [];').replace(/const API_URL = "[^"]+"/,'const API_URL = "/api"').replace('<script src="data.js"></script>',gateHtmlForTest(enc,today)).replace(/renderEvents\(\);\s*\nsetView\("today"\);/,'/* unlock renders */');writeBundle(path.join(target,'comlist.html'),source,path.join(root,'_assets'));
 const server=http.createServer(async(req,res)=>{if(req.url==='/api'){let raw='';for await(const part of req)raw+=part;const b=JSON.parse(raw);const j=b.action==='taskState'?{ok:true,done:{},date:b.date}:b.action==='read'?{ok:true,records:[],events:[]}:{ok:false};res.setHeader('Content-Type','application/json');res.end(JSON.stringify(j));return;}try{const rel=new URL(req.url,'http://local').pathname.slice(1)||'comlist.html',file=path.resolve(target,rel);if(!file.startsWith(target+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('not found');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const runtime=process.env.CODEX_NODE_MODULES||'C:/Users/ryupr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules',{chromium}=require(path.join(runtime,'playwright'));const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe',chromium.executablePath()].find(f=>fs.existsSync(f));const browser=await chromium.launch({headless:true,executablePath});const results=[];
 try{for(const width of [1280,390]){const context=await browser.newContext({viewport:{width,height:900}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/comlist.html');await page.locator('#lockpass').fill('calendar-fixture-pass');await page.locator('#lockbtn').click();await page.waitForFunction(()=>document.getElementById('lockgate').style.display==='none');const schedule=page.locator('[data-section=schedule]');assert.equal(await schedule.locator('.today-schedule-item').count(),2);assert.match(await schedule.textContent(),/検証用・日またぎイベント/);assert.match(await schedule.textContent(),/継続中/);assert.match(await schedule.textContent(),/08:00〜08:30/);assert.equal(await schedule.locator('.today-schedule-description').count(),1);await schedule.locator('summary').click();assert.equal(await schedule.locator('.today-schedule-description div').isVisible(),true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(target,width===1280?'pc.png':'mobile.png'),fullPage:true});await page.evaluate(()=>{setView('garden');SELECTED=plantKey(DATA[0]);renderPanel();});assert.equal(await page.locator('#gdpanel .friend-advice').count(),1);assert.match(await page.locator('#gdpanel .friend-advice').textContent(),/次に聞く質問/);assert.equal(await page.locator('#gdpanel .friend-advice input,#gdpanel .friend-advice textarea').count(),0);await page.locator('#gdpanel').screenshot({path:path.join(target,'advice-'+width+'.png')});assert.deepEqual(errors,[]);results.push({width,todayTitles:true,ongoingMultiDay:true,emptyDetailsOmitted:true,detailsToggle:true,noOverflow:true,readOnlyAdvice:true});await context.close();}}finally{await browser.close();await new Promise(r=>server.close(r));}
 const report={results,productionRequests:0};fs.writeFileSync(path.join(target,'result.json'),JSON.stringify(report,null,2));return report;
}
module.exports={run};if(require.main===module)run().then(r=>console.log('CALENDAR_BROWSER: OK '+JSON.stringify(r))).catch(e=>{console.error(e);process.exitCode=1;});
